import math

# Setting Display game
RES = WIDTH, HEIGHT = 1200, 600
SETENGAH_WIDTH = WIDTH // 2
SETENGAH_HEIGHT = HEIGHT // 2
FPS = 0

# Setting Pemain
PLAYER_POS = 1.5, 2 # posisi pemain di minimap
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_SIZE_SCALE = 60
PLAYER_ROTSPEED = 0.002
PLAYER_MAX_HEALTH = 100

# Setting mouse
MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_KIRI = 100
MOUSE_BORDER_KANAN = WIDTH - MOUSE_BORDER_KIRI

# Setting lantai
WARNA_LANTAI = (30, 30, 30)

# Setting raycast
FOV = math.pi / 3
SETENGAH_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
SETENGAH_NUM_RAYS = NUM_RAYS //2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

# Setting untuk NPC
JARAK_SCREEN = SETENGAH_WIDTH / math.tan(SETENGAH_FOV)
SKALA = WIDTH // NUM_RAYS

# Setting tekstur
TEXTURE_SIZE = 256
SETENGAH_TEXTURE_SIZE = TEXTURE_SIZE // 2